GestionProduits/GestionProduits/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('lesProduits/',include("LesProduits.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
]

GestionProduits/LesProduits/urls.py
from django.urls import path

from . import views
from django.views.generic import TemplateView

urlpatterns = [
    #path("home/<name>", views.HomeParamView.as_view(), name="index"),
    #path("home/", views.home, name="home"),
    path("home",views.HomeView.as_view(), name="home"),

    # Les produits : 
    path("products", views.ProductListView.as_view(), name="product-list"),
    path("product/<pk>",views.ProductDetailView.as_view(), name="product-detail"),
    path("products/<pk>/update/",views.ProductUpdateView.as_view(), name="product-update"),
    path("products/<pk>/delete/",views.ProductDeleteView.as_view(), name="product-delete"),
    path("products/add/",views.ProductCreateView.as_view(), name="product-add"),

    # Authentification : 
    path('login/', views.ConnectView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('logout/', views.DisconnectView.as_view(), name='logout'),

    # Attributs :
    path("attributs/",views.ProductAttributeListView.as_view(), name="attribut-list"),
    path("attribut/<pk>",views.ProductAttributeDetailView.as_view(), name="attribute-detail"),
    path("attribut/<pk>/delete/",views.ProductAttributeDeleteView.as_view(), name="attribute-delete"),
    path("attributs/<pk>/update/",views.ProductAttributeUpdateView.as_view(), name="attribute-update"),
    path("attribut/add/",views.ProductAttributeCreateView.as_view(), name="attribut-add"),
    

    # Items : 
    path("items/",views.ProductItemListView.as_view(), name="item-list"),
    path("item/<pk>",views.ProductItemDetailView.as_view(), name="item-detail"),
    path("item/<pk>/delete/",views.ProductItemDeleteView.as_view(), name="item-delete"),
    path("item/<pk>/update/",views.ProductItemUpdateView.as_view(), name="item-update"),
    path("item/add/",views.ProductItemCreateView.as_view(), name="item-add"),

    #Achat
    path("achats/<int:productitem_id>/",views.AchatView.as_view(), name="achat_produit"),

    # Support : 
    path("about",views.AboutView.as_view(), name='about-page'),
    path('contact/', views.ContactView, name='contact'),

    # Fournisseurs :
    path("providers",views.ProviderListView.as_view(), name="provider-list"),
    path("provider/<pk>",views.ProviderDetailView.as_view(), name="provider-detail"),
    path("provider/add/",views.ProviderCreateView.as_view(), name="provider-add"),
    path("provider/<pk>/update/",views.ProviderUpdateView.as_view(), name="provider-update"),
    path("provider/<pk>/delete/",views.ProviderDeleteView.as_view(), name="provider-delete"),

    # Prix fournisseurs :
    path("providerPrice/<pk>/update/",views.ProviderProductPriceUpdateView.as_view(), name="providerPrice-update"),
    path("providerPrice/<pk>/delete/",views.ProviderProductPriceDeleteView.as_view(), name="providerPrice-delete"),
    path("providerPrice/<int:provider_id>/add/",views.ProviderProductPriceCreateView.as_view(), name="providerPrice-add"),

    # Commandes :
    path("orders/<int:provider_id>/add",views.OrderCreateView.as_view(), name="order-add"),
    path("orders",views.OrderListView.as_view(), name="order-list"),
    path("order/<pk>",views.OrderDetailView.as_view(), name="order-detail"),
    path("order/<pk>/delete/",views.OrderDeleteView.as_view(), name="order-delete"),
    path("order/<pk>/update/",views.OrderUpdateView.as_view(), name="order-update"),

    # OrderProductItem : 
    path("orderProductItem/add/<int:order_id>",views.OrderProductItemCreateView.as_view(), name="orderProductItem-add"),

    # Actions commandes : 
    path("order/<int:order_id>/passed",views.order_passed, name="order-passed"),
    path("order/<int:order_id>/received",views.order_received, name="order-received"),

]

GestionProduits/LesProduits/models.py
from django.db import models
from django.utils import timezone

PRODUCT_STATUS = (
    (0, 'Offline'),
    (1, 'Online'),
    (2, 'Out of stock')              
)

COMMANDE_STATUS = (
    (0, 'En preparation'),
    (1, 'Passée'),
    (2, 'Reçue'),              
)

# Create your models here.
"""
    Status : numero, libelle
"""
class Status(models.Model):
    numero  = models.IntegerField()
    libelle = models.CharField(max_length=100)
          
    def __str__(self):
        return "{0} {1}".format(self.numero, self.libelle)
    
"""
Produit : nom, code, etc.
"""
class Product(models.Model):

    class Meta:
        verbose_name = "Produit"

    name          = models.CharField(max_length=100)
    code          = models.CharField(max_length=10, null=True, blank=True, unique=True)
    price_ht      = models.DecimalField(max_digits=8, decimal_places=2,  null=True, blank=True, verbose_name="Prix unitaire HT")
    price_ttc     = models.DecimalField(max_digits=8, decimal_places=2,  null=True, blank=True, verbose_name="Prix unitaire TTC")
    status        = models.SmallIntegerField(choices=PRODUCT_STATUS, default=0)
    date_creation =  models.DateTimeField(blank=True, verbose_name="Date création", default=timezone.now) 
    
    def __str__(self):
        return "{0} {1}".format(self.name, self.code)

"""
    Déclinaison de produit déterminée par des attributs comme la couleur, etc.
"""
class ProductItem(models.Model):
    
    class Meta:
        verbose_name = "Déclinaison Produit"

    color   = models.CharField(max_length=100)
    code    = models.CharField(max_length=10, null=True, blank=True, unique=True)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    attributes  = models.ManyToManyField("ProductAttributeValue", related_name="product_item", blank=True)
    quantity = models.PositiveIntegerField("Quantité", default=0, null=True, blank=True)
       
    def __str__(self):
        attributes_str = ", ".join([attr.value for attr in self.attributes.all()])
        return "{0} {1}".format(self.product.name, attributes_str)
    
class ProductAttribute(models.Model):
    """
    Attributs produit
    """
    
    class Meta:
        verbose_name = "Attribut"
        
    name =  models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    
class ProductAttributeValue(models.Model):
    """
    Valeurs des attributs
    """
    
    class Meta:
        verbose_name = "Valeur attribut"
        ordering = ['position']
        
    value              = models.CharField(max_length=100)
    product_attribute  = models.ForeignKey('ProductAttribute', verbose_name="Unité", on_delete=models.CASCADE)
    position           = models.PositiveSmallIntegerField("Position", null=True, blank=True)
     
    def __str__(self):
        return "{0} [{1}]".format(self.value, self.product_attribute)
    
class Provider(models.Model):
    """
    Fournisseur
    """
    
    class Meta:
        verbose_name = "Fournisseur"
        
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)

    def __str__(self):
        return "{0} [{1}]".format(self.name, self.address)
    
class ProviderProductPrice(models.Model):
    """
    Prix d'achat d'un produit chez un fournisseur
    """
    
    class Meta:
        verbose_name = "Prix d'achat"
        
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    provider = models.ForeignKey('Provider', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2,  null=True, blank=True, verbose_name="Prix unitaire HT")
    
    def __str__(self):
        return "{0} [{1}]".format(self.product, self.provider)
    
class Order(models.Model):
    """
    Commande
    """
    
    class Meta:
        verbose_name = "Commande"
        
    date_creation =  models.DateTimeField(blank=True, verbose_name="Date création", default=timezone.now) 
    status = models.SmallIntegerField(choices=COMMANDE_STATUS, default=0)
    name = models.CharField(max_length=100)
    provider = models.ForeignKey('Provider', on_delete=models.CASCADE)
    
    def __str__(self):
        return "{0} [{1}]".format(self.name, self.date_creation)

    def get_status_display(self):
        return dict(COMMANDE_STATUS).get(self.status)
    
class OrderProductItem(models.Model):
    """
    Produit commandé
    """
    
    class Meta:
        verbose_name = "Produit commandé"
        
    productItem = models.ForeignKey('ProductItem', on_delete=models.CASCADE)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField("Quantité", default=0, null=True, blank=True)

    def __str__(self):
        return "{0} [{1}]".format(self.productItem, self.order)
    
    
    


#python3 manage.py makemigrations LesProduits
#python3 manage.py sqlmigrate LesProduits 0001
#python manage.py migrate

GestionProduits/templates/Attributs/delete_attibute.html
{% extends 'base.html' %}

{% block contenu %}
    <h1>Suppression d'un produit</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Etes-vous sûr de vouloir supprimer le produit : {{ object.name }} ?</p>
        <button type="submit" class="btn btn-success mt-2">Confirmer</button>
        <a href="{% url 'attribut-list' %}" class="btn btn-danger mt-2">Annuler</a>
    </form>
{% endblock %}

GestionProduits/templates/Attributs/delete_attribute.html
{% extends 'base.html' %}

{% block contenu %}
    <h1>Suppression d'un produit</h1>
    <form action="" method="post">
        {% csrf_token %}
        <p>Etes-vous sûr de vouloir supprimer le produit : {{ object.name }} ?</p>
        <button type="submit" class="btn btn-success mt-2">Confirmer</button>
        <a href="{% url 'attribut-list' %}" class="btn btn-danger mt-2">Annuler</a>
    </form>
{% endblock %}

GestionProduits/templates/Attributs/detail_attribute.html
{% extends 'base.html' %}

{% block title %}
    Mon application DJANGO
{% endblock %}

{% block menu %}
    <h1 class="display-4">{{ titremenu }}</h1>
{% endblock %}

{% block contenu %}
    <div class="container mt-4">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <h2 class="mb-4">{{ productattribute.name }}</h2>
                <ul class="list-group mb-4">
                    {% for value in values %}
                        <li class="list-group-item">
                            {{ value.value }} <span class="badge badge-secondary">Position: {{ value.position }}</span>
                        </li>
                    {% empty %}
                        <li class="list-group-item">Aucune valeur disponible pour cet attribut.</li>
                    {% endfor %}
                </ul>
                <a href="{% url 'attribut-list' %}" class="btn btn-primary">Retour</a>
            </div>
        </div>
    </div>
{% endblock %}

GestionProduits/templates/Attributs/list_ProductAttribute.html
{% extends 'base.html' %}

{% block contenu %}
<table class="table">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Valeurs</th>
            <th>Position</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for attribute in productattributes %}
        <tr>
            <td>{{ attribute.name }}</td>
            <td>
                {% for value in attribute.productattributevalue_set.all %}
                <p>{{ value.value }}</p>
                {% empty %}
                <p>Aucune valeur</p>
                {% endfor %}
            </td>
            <td>
                {% for value in attribute.productattributevalue_set.all %}
                <p>{{ value.position }}</p>
                {% empty %}
                <p>Aucune valeur</p>
                {% endfor %}
            </td>
            <td>
                <a href="{% url 'attribute-detail' attribute.id %}" class="btn btn-primary mt-2">Détails</a>
                {% if user.is_superuser %}
                    <a href="{% url 'attribute-delete' attribute.id %}" class="btn btn-danger mt-2">Supprimer</a>
                    <a href="{% url 'attribute-update' attribute.id %}" class="btn btn-secondary mt-2">modifier</a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% if user.is_superuser %}
    <a href="{% url 'attribut-add'  %}" class="btn btn-primary mt-2">Ajouter un attribue</a>
{% endif %}
{% endblock %}

GestionProduits/templates/Attributs/new_attributs.html
{% extends 'base.html' %}

{% block contenu %}
    <h1>Création d'un nouvel attribut</h1>
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-2">Créer</button>
    </form>
{% endblock %}

GestionProduits/templates/Attributs/update_attribut.html
{% extends 'base.html' %}

{% block contenu %}
    <h1>Modification d'un item</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success mt-2">Modifier</button>
    </form>
{% endblock %}